apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: f5-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: f5-nginx
    spec:
      containers:
      - name: f5-nginx
        image: harbor.syspks.com/yelb-demo/nginx:0.4
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: f5-nginx
  labels:
    run: f5-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: f5-nginx
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-nginx
  namespace: default
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 80,
          "serviceName": "f5-nginx",
          "healthMonitors": [{
            "interval": 30,
            "protocol": "http",
            "send": "GET HTTP/1.1/\r\n",
            "recv": "200|OK",
            "timeout": 120
          }]
        },
        "frontend": {
          "virtualAddress": {
            "port": 8080,
            "bindAddr": "10.9.25.71"
          },
          "partition": "kubernetes",
          "balance": "least-connections-member",
          "mode": "http"
        }
      }
    }
